### ISSUE TITLE
 Crash with TensorFlow 1.2.0-rc0-gpu

### ISSUE THREAD

**Issue by lipeng31** [Unisound/SampleRNN#5]
使用 docker image `tensorflow/tensorflow:1.0.0-gpu` 可以正常运行，使用 `tensorflow/tensorflow:1.2.0-rc0-gpu` 时会崩溃：
```
Creating model On Gpu:0.
Traceback (most recent call last):
  File "train.py", line 414, in <module>
    main()
  File "train.py", line 306, in main
    l2_regularization_strength=args.l2_regularization_strength)
  File "/workspace/samplernn/model.py", line 185, in loss_SampleRnn
    self._create_network_SampleRnn( train_big_frame_state, train_frame_state)
  File "/workspace/samplernn/model.py", line 168, in _create_network_SampleRnn
    input_sequences = input_sequences)
  File "/workspace/samplernn/model.py", line 97, in _create_network_Frame
    (frame_cell_output, frame_state) = self.cell(cell_input, frame_state)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 165, in __call__
    return super(_RNNCell, self).__call__(inputs, state)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 439, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 118, in call
    bias_ones, self._kernel_initializer))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 1022, in _linear
    initializer=kernel_initializer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 360, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell_impl.py", line 168, in _rnn_get_variable
    variable = getter(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 669, in _get_single_variable
    found_var.get_shape()))
ValueError: Trying to share variable BigFrame_layer/BIG_FRAME_RNN/gru_cell/gates/weights, but specified shape (2048, 2048) and found shape (1032, 2048).
```

**Comment by pineking** [comment]
@xuerq https://stackoverflow.com/questions/42644724/trying-to-share-variable-basic-rnn-cell-weights-but-specified-shape-error 看下是不是和这个类似需要  reinitialize？

**Comment by xuerq** [comment]
@pineking 具体原因还不清楚，打算假期时间调试一下
